# Generated by Django 5.1.1 on 2025-10-21 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('hybrid', 'hybrid'), ('electric', 'electric')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=20)),
                ('drive', models.CharField(choices=[('fwd', 'fwd'), ('rwd', 'rwd'), ('awd', 'awd')], default='fwd', max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('vin_hash', models.CharField(blank=True, max_length=64)),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('sold', 'sold')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car')),
            ],
        ),
    ]
