# Generated by Django 5.1.1 on 2025-10-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('reserved', 'Резерв'), ('sold', 'Продано')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('wagon', 'Универсал'), ('suv', 'Внедорожник/SUV'), ('coupe', 'Купе'), ('cabrio', 'Кабриолет'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('van', 'Фургон'), ('other', 'Другое')], default='sedan', max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('after_accident', 'После ДТП'), ('for_parts', 'На запчасти')], default='used', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Первая регистрация'),
        ),
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.CharField(blank=True, max_length=120, verbose_name='Поколение'),
        ),
        migrations.AddField(
            model_name='car',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Происхождение (страна)'),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регистрация (страна)'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(default='EUR', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], default='fwd', max_length=10, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём двигателя, см³'),
        ),
        migrations.AlterField(
            model_name='car',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('lpg', 'Газ/Бензин'), ('other', 'Другое')], default='petrol', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, €'),
        ),
        migrations.AlterField(
            model_name='car',
            name='source',
            field=models.CharField(default='manual', max_length=20, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('sold', 'Продано')], default='draft', max_length=20, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Вариатор')], default='manual', max_length=20, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='VIN (hash/маска)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='cars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
