# Generated by Django 5.1.1 on 2025-10-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото (локально)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Фото (внешний URL)'),
        ),
    ]
