# Generated by Django 5.1.1 on 2025-10-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_photo_image_photo_image_file_photo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
