# Generated by Django 5.1.1 on 2025-10-25 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_update_fuel_type_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['car_id', 'sort_order', 'id'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type_code',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('lpg_propane', 'Газ / Бензин (пропан)'), ('cng_methane', 'Газ / Бензин (метан)'), ('hybrid', 'Гибрид'), ('electric', 'Электричество'), ('phev_petrol', 'Плагин-гибрид (бензин)'), ('phev_diesel', 'Плагин-гибрид (дизель)'), ('mhev_petrol', 'Мягкий-гибрид (бензин)'), ('mhev_diesel', 'Мягкий-гибрид (дизель)'), ('other', 'Другое')], db_index=True, default='', max_length=32, verbose_name='Тип топлива (код)'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Тип топлива (лейбл для фронта)'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type_raw',
            field=models.TextField(blank=True, default='', verbose_name='Топливо (сырой текст из 999)'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_code',
            field=models.CharField(blank=True, choices=[('automatic', 'Автомат'), ('manual', 'Механика'), ('robot', 'Робот'), ('cvt', 'Вариатор'), ('other', 'Другое')], db_index=True, default='', max_length=32, verbose_name='КПП (код)'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='КПП (лейбл для фронта)'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_raw',
            field=models.TextField(blank=True, default='', verbose_name='КПП (сырой текст из 999)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Доступность / наличие'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Тип кузова (норм.)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Состояние (норм.)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='currency',
            field=models.CharField(default='EUR', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Привод (норм.)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_cc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём двигателя, см³'),
        ),
        migrations.AlterField(
            model_name='car',
            name='external_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID на стороне источника'),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Первая регистрация (дата)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Поколение / серия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Город / Локация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_km',
            field=models.IntegerField(default=0, verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='origin_country',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность, л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена в EUR'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_country',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Страна регистрации'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='car',
            name='source',
            field=models.CharField(db_index=True, default='999', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(db_index=True, default='published', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='VIN (усечённый/хеш)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска (числом)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Локальный файл'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.TextField(blank=True, default='', verbose_name='Ссылка на картинку (999)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главное фото?'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
