# Generated by Django 5.1.1 on 2025-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_photo_url',
            field=models.TextField(blank=True, default='', help_text='URL первой (основной) фотографии объявления с 999.md', verbose_name='Главное фото (URL)'),
        ),
    ]
