# Generated by Django 5.1.1 on 2025-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_main_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='False = больше не показываем на сайте (снято с 999.md)', verbose_name='Активно на витрине?'),
        ),
        migrations.AddField(
            model_name='car',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последний раз замечено в источнике'),
        ),
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Примерная дата продажи/снятия с продажи'),
        ),
    ]
