# Generated by Django 5.1.1 on 2025-10-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_active_car_last_seen_at_car_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type_canonical',
            field=models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('hybrid_petrol', 'hybrid_petrol'), ('hybrid_diesel', 'hybrid_diesel'), ('phev_petrol', 'phev_petrol'), ('phev_diesel', 'phev_diesel'), ('electric', 'electric'), ('lpg', 'lpg'), ('cng', 'cng'), ('hydrogen', 'hydrogen')], db_index=True, default='', help_text='Единый нормализованный код топлива для фронта/фильтров', max_length=32, verbose_name='Тип топлива (канон.)'),
        ),
    ]
